#!/bin/bash

# Get the current branch name
branch_name=$(git symbolic-ref --short HEAD 2>/dev/null)

# Check if the branch name is not empty
if [ -n "$branch_name" ]; then
  # Prepend the branch name to the commit message
  sed -i.bak -e "1s/^/[$branch_name] /" "$1"
fi

