[[mgr.prepend_keymap]]
on   = [ "<C-s>" ]
run  = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

[[mgr.prepend_keymap]]
on  = [ "K" ]
run = "plugin --sync parent-arrow --args=-1"

[[mgr.prepend_keymap]]
on  = [ "J" ]
run = "plugin --sync parent-arrow --args=1"

[[mgr.prepend_keymap]]
on   = [ "g", "r" ]
run  = 'cd ~/Documents/repo/'
desc = "Go to repo"

[[mgr.prepend_keymap]]
on = [ "m" ]
run = "plugin relative-motions"
desc = "Trigger a new relative motion"

[[mgr.prepend_keymap]]
on   = [ "f","g" ]
run  = "plugin fg"
desc = "find file by content"

[[mgr.prepend_keymap]]
on   = [ "f","f" ]
run  = "plugin fg --args='fzf'"
desc = "find file by file name"

[[mgr.prepend_keymap]]
on   = [ "t","h" ]
run  = "hidden"
desc = "[T]oggle [H]idden files"

[[input.prepend_keymap]]
on   = [ "<Esc>" ]
run  = "close"
desc = "Cancel input"

[[mgr.prepend_keymap]]
on  = [ "T" ]
run = "plugin --sync max-preview"

[[mgr.prepend_keymap]]
on  = [ "K" ]
run = "plugin --sync parent-arrow --args=-1"

[[mgr.prepend_keymap]]
on  = [ "J" ]
run = "plugin --sync parent-arrow --args=1"
